services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 4000:27017
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672